repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [check, .]
        pass_filenames: false
      - id: ruff-format
        args: [--check, .]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uvx pyright
        language: system
        pass_filenames: false
