repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-format
        args: [.]
        pass_filenames: false
  - repo: local
    hooks:
      - id: ruff-fix-nonblocking
        name: ruff-fix-nonblocking
        entry: sh -c 'uvx ruff check --fix . || true'
        language: system
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-check
        args: [.]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uvx pyright
        language: system
        pass_filenames: false
